ccflags-y += -Idrivers/media/platform/msm/camera_v2_vivo_51
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vivo_51/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vivo_51/sensor/io
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
