ccflags-y += -Idrivers/media/platform/msm/camera_v2_vivo_51
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vivo_51/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_vivo_51/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
