#
# Makefile for the input misc drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_BBK_SENSORS_MAG_YAS533)	+= yas_mag_drv-yas532.o yas_mag_kernel.o
obj-$(CONFIG_BBK_SENSORS_LIS3DH)		+= lis3dh_acc.o
obj-$(CONFIG_BBK_SENSORS_TMD277X)		+= tmd2771.o
obj-$(CONFIG_BBK_SENSORS_MAG_AKM8963)		+= akm8963.o
obj-$(CONFIG_BBK_SENSORS_MAG_AKM09912)		+= akm09912.o
obj-$(CONFIG_BBK_SENSORS_MAG_ALPS007)		+= hscdtd007a.o
obj-y += vivo_logger.o
obj-y += interface.o
obj-y += config/
obj-y += across.o
